# This compose.yaml file starts the core infrastructure:
# - RabbitMQ for message queuing
# - Server for WebSocket and gRPC services
# - Broker for message routing 
# - Frontend web application
#
# NOTE: Agents should be started separately outside of Docker Compose
# to allow for dynamic configuration and API key management.
# See README.md and GETTING_STARTED.md for instructions on running agents.
#
# Start with: docker compose up --build

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      # Enable BuildKit features
      args:
        BUILDKIT_INLINE_CACHE: 1
      # Enable BuildKit cache mounts
      # For local development, type=local is used.
      # For CI/CD, consider adding registry-based caching for faster builds:
      # cache_from:
      #   - type=registry,ref=your-registry/server-cache
      #   - type=local,src=/tmp/docker-cache/server
      # cache_to:
      #   - type=registry,ref=your-registry/server-cache,mode=max
      cache_from:
        - type=local,src=/tmp/docker-cache/server
    ports:
      - "8765:8765"  # WebSocket
      - "50051:50051" # gRPC
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - WEBSOCKET_HOST=0.0.0.0
      - GRPC_HOST=0.0.0.0
      - HOST=0.0.0.0
      - PORT=8765
      - GRPC_PORT=50051
      - GRPC_DEBUG=0
      - GRPC_DEADLINE_SECONDS=30
      - LOG_FILE=/var/log/server.log
    volumes:
      - ./shared_models:/app/shared_models
      - ./shared/protos:/app/shared/protos
      - ./logs:/var/log
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8765/health"]
      interval: 60s
      timeout: 10s
      retries: 20
      start_period: 20s
    depends_on:
      rabbitmq:
        condition: service_healthy

  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
      # Enable BuildKit features
      args:
        BUILDKIT_INLINE_CACHE: 1
      # Enable BuildKit cache mounts
      # For local development, type=local is used.
      # For CI/CD, consider adding registry-based caching for faster builds:
      # cache_from:
      #   - type=registry,ref=your-registry/broker-cache
      #   - type=local,src=/tmp/docker-cache/broker
      # cache_to:
      #   - type=registry,ref=your-registry/broker-cache,mode=max
      cache_from:
        - type=local,src=/tmp/docker-cache/broker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - GRPC_HOST=server
      - GRPC_PORT=50051
      - GRPC_DEBUG=0
      - GRPC_DEADLINE_SECONDS=30
    volumes:
      - ./shared_models:/app/shared_models
      - ./shared/protos:/app/shared/protos
    depends_on:
      server:
        condition: service_healthy
    
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      # Enable BuildKit features
      args:
        BUILDKIT_INLINE_CACHE: 1
      # Enable BuildKit cache mounts
      # For local development, type=local is used.
      # For CI/CD, consider adding registry-based caching for faster builds:
      # cache_from:
      #   - type=registry,ref=your-registry/frontend-cache
      #   - type=local,src=/tmp/docker-cache/frontend
      # cache_to:
      #   - type=registry,ref=your-registry/frontend-cache,mode=max
      cache_from:
        - type=local,src=/tmp/docker-cache/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://localhost:8765/ws
      - VITE_API_URL=http://localhost:8765
    depends_on:
      server:
        condition: service_healthy